from tkinter import *
from PIL import Image,ImageTk
root=Tk()
root.columnconfigure(1,weight=2)
root.columnconfigure(0,weight=1)
root.geometry('1000x1000')
root.title('Home')
usernameLabel=Label(root,text='Enter Username:').grid(row=2,column=1,sticky=W)
passwordLabel=Label(root,text='Enter Password:').grid(row=3,column=1,sticky=W)
username=Entry(root,text='username').grid(row=2,column=1)
password=Entry(root,text='password').grid(row=3,column=1)
submit=Button(root,text='SUBMIT').grid(row=4,column=1)
pic=PhotoImage(file='butterfly.png')
img1=Image.open('health fitness cartoon.png')
img1=img1.resize((150,150))
img1=ImageTk.PhotoImage(img1)
imageLabel=Label(root,image=img1).grid(row=2,column=0)
root.iconphoto(False,pic)
root.mainloop()
